<?php
// verify_formc.php — standalone public verification page
error_reporting(E_ALL);
ini_set('display_errors', 1); // temporary to see errors

// Direct database connection (adjust credentials if needed)
require_once __DIR__ . '/includes/connection.php'; // this should create $pdo

// If your connection.php uses a different variable, adjust below
// For example, some use $conn or $db. Check your connection.php content.

$ref = $_GET['ref'] ?? '';
if (empty($ref) || !preg_match('/^ProSensiaB(\d{4})$/', $ref, $matches)) {
    http_response_code(400);
    die('Invalid reference number.');
}

$refNum = (int)$matches[1];
$formId = $refNum - 3000; // ProSensiaB3001 = id 1

try {
    $stmt = $pdo->prepare('
        SELECT f.*, u.name, u.email, p.father_name, p.cnic, p.reg_number, p.department, p.semester, p.address, p.phone
        FROM form_c f
        JOIN users u ON u.id = f.user_id
        LEFT JOIN profiles p ON p.user_id = u.id
        WHERE f.id = ? AND f.status = "approved"
    ');
    $stmt->execute([$formId]);
    $form = $stmt->fetch();
} catch (PDOException $e) {
    http_response_code(500);
    die('Database error: ' . $e->getMessage());
}

if (!$form) {
    http_response_code(404);
    die('Form C not found or not approved.');
}

// Helper function to generate base URL (similar to base_url() but standalone)
function site_url($path = '') {
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'];
    return $protocol . '://' . $host . '/' . ltrim($path, '/');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form C Verification – ProSensia</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background: #f5f3ef; font-family: 'Inter', sans-serif; padding: 2rem; }
        .verify-card { max-width: 900px; margin: auto; background: white; border-radius: 24px; box-shadow: 0 10px 30px rgba(0,0,0,0.05); padding: 2rem; }
        .badge-verified { background: #10b981; color: white; }
        hr { margin: 1.5rem 0; }
    </style>
</head>
<body>
<div class="verify-card">
    <div class="d-flex justify-content-between align-items-center">
        <h2>Internship Placement Proforma</h2>
        <span class="badge badge-verified px-3 py-2">✓ Verified – Official Document</span>
    </div>
    <p class="text-muted">Reference: <strong><?= htmlspecialchars($ref) ?></strong> · Generated by ProSensia Portal</p>
    <hr>

    <h5>Student Information</h5>
    <div class="row mb-3">
        <div class="col-md-6"><strong>Name:</strong> <?= htmlspecialchars($form['name']) ?></div>
        <div class="col-md-6"><strong>Father Name:</strong> <?= htmlspecialchars($form['father_name'] ?? '—') ?></div>
        <div class="col-md-6"><strong>Registration #:</strong> <?= htmlspecialchars($form['reg_number'] ?? '—') ?></div>
        <div class="col-md-6"><strong>Department:</strong> <?= htmlspecialchars($form['department'] ?? 'Electrical and Computer Engineering') ?></div>
        <div class="col-md-6"><strong>CNIC #:</strong> <?= htmlspecialchars($form['cnic'] ?? '—') ?></div>
        <div class="col-md-6"><strong>Contact:</strong> <?= htmlspecialchars($form['phone'] ?? '—') ?></div>
        <div class="col-md-6"><strong>Email:</strong> <?= htmlspecialchars($form['email']) ?></div>
        <div class="col-md-6"><strong>Semester:</strong> <?= htmlspecialchars($form['semester'] ?? '—') ?></div>
        <div class="col-12"><strong>Present Address:</strong> <?= nl2br(htmlspecialchars($form['address'] ?? '—')) ?></div>
    </div>

    <h5>Employer Details</h5>
    <div class="row mb-3">
        <div class="col-md-6"><strong>Employer Name:</strong> <?= htmlspecialchars($form['employer_name'] ?? '—') ?></div>
        <div class="col-md-6"><strong>Department:</strong> <?= htmlspecialchars($form['employer_dept'] ?? '—') ?></div>
        <div class="col-md-6"><strong>Joining Date:</strong> <?= htmlspecialchars($form['joining_date'] ?? '—') ?></div>
        <div class="col-md-6"><strong>Internship Period:</strong> <?= htmlspecialchars($form['start_date'] ?? '') ?> to <?= htmlspecialchars($form['end_date'] ?? '') ?></div>
    </div>

    <hr>
    <p class="text-muted small">This document is digitally signed and issued by ProSensia. No physical stamp required. <br> Verification timestamp: <?= date('Y-m-d H:i:s') ?></p>
    <div class="text-center mt-3">
        <a href="<?= site_url('intern/formc_pdf.php?uid=' . $form['user_id']) ?>" class="btn btn-primary btn-sm">Download original PDF</a>
    </div>
</div>
</body>
</html>