<?php
// verify_admit.php — Public Admit Card Verification Page
error_reporting(E_ALL);
ini_set('display_errors', 0);  // hide errors in production

require_once __DIR__ . '/includes/connection.php'; // creates $pdo

$uid = isset($_GET['uid']) ? (int)$_GET['uid'] : 0;
if ($uid <= 0) {
    http_response_code(400);
    die('Invalid request.');
}

// Fetch user + profile + form_c + enrollment
try {
    $stmt = $pdo->prepare('
        SELECT u.name, u.email, u.status,
               p.father_name, p.cnic, p.reg_number, p.department, p.semester, p.phone, p.address,
               f.employer_name, f.employer_dept, f.joining_date, f.start_date, f.end_date, f.status AS form_status,
               e.track, e.batch
        FROM users u
        LEFT JOIN profiles p ON p.user_id = u.id
        LEFT JOIN form_c f ON f.user_id = u.id
        LEFT JOIN enrollments e ON e.user_id = u.id
        WHERE u.id = ?
    ');
    $stmt->execute([$uid]);
    $data = $stmt->fetch(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    http_response_code(500);
    die('Database error.');
}

if (!$data) {
    http_response_code(404);
    die('No record found.');
}

// Only show if form_c is submitted/approved (admit card is valid)
$formStatus = strtolower(trim($data['form_status'] ?? ''));
if (!in_array($formStatus, ['submitted', 'approved'])) {
    http_response_code(404);
    die('Admit card not available for this candidate.');
}

// Prepare data for display
$name         = $data['name'] ?? '';
$email        = $data['email'] ?? '';
$father       = $data['father_name'] ?? '';
$cnic         = $data['cnic'] ?? '';
$regNo        = $data['reg_number'] ?? '';
$department   = $data['department'] ?? 'Electrical and Computer Engineering';
$semester     = $data['semester'] ?? '';
$phone        = $data['phone'] ?? '';
$address      = $data['address'] ?? '';
$employer     = $data['employer_name'] ?? '';
$employerDept = $data['employer_dept'] ?? '';
$joining      = $data['joining_date'] ?? '';
$startDate    = $data['start_date'] ?? '';
$endDate      = $data['end_date'] ?? '';
$track        = $data['track'] ?? '';
$batch        = $data['batch'] ?? '';

// Download URL for the admit card PDF
$pdfUrl = 'intern/admit_card.php';  // relative to root, or adjust if needed
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admit Card Verification – ProSensia</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background: #f5f3ef; font-family: 'Inter', sans-serif; padding: 2rem; }
        .verify-card {
            max-width: 900px; margin: auto; background: white;
            border-radius: 24px; box-shadow: 0 10px 30px rgba(0,0,0,0.05);
            padding: 2rem;
        }
        .badge-verified { background: #d4a84c; color: #fff; }
        .gold-text { color: #b2892e; }
        hr { margin: 1.5rem 0; }
    </style>
</head>
<body>
<div class="verify-card">
    <div class="d-flex justify-content-between align-items-center">
        <h2 class="gold-text">Admit Card</h2>
        <span class="badge badge-verified px-3 py-2">✓ Verified – Official Document</span>
    </div>
    <p class="text-muted">Reference: ADMIT-<?= str_pad($uid, 6, '0', STR_PAD_LEFT) ?> · Generated by ProSensia Portal</p>
    <hr>

    <h5 class="gold-text">Candidate Information</h5>
    <div class="row mb-3">
        <div class="col-md-6"><strong>Name:</strong> <?= htmlspecialchars($name) ?></div>
        <div class="col-md-6"><strong>Father Name:</strong> <?= htmlspecialchars($father) ?></div>
        <div class="col-md-6"><strong>Registration #:</strong> <?= htmlspecialchars($regNo) ?></div>
        <div class="col-md-6"><strong>CNIC #:</strong> <?= htmlspecialchars($cnic) ?></div>
        <div class="col-md-6"><strong>Department:</strong> <?= htmlspecialchars($department) ?></div>
        <div class="col-md-6"><strong>Semester:</strong> <?= htmlspecialchars($semester) ?></div>
        <div class="col-md-6"><strong>Contact:</strong> <?= htmlspecialchars($phone) ?></div>
        <div class="col-md-6"><strong>Email:</strong> <?= htmlspecialchars($email) ?></div>
        <div class="col-12"><strong>Address:</strong> <?= nl2br(htmlspecialchars($address)) ?></div>
    </div>

    <h5 class="gold-text">Internship Details</h5>
    <div class="row mb-3">
        <?php if ($track): ?>
        <div class="col-md-6"><strong>Track:</strong> <?= htmlspecialchars($track) ?></div>
        <?php endif; ?>
        <?php if ($batch): ?>
        <div class="col-md-6"><strong>Batch:</strong> <?= htmlspecialchars($batch) ?></div>
        <?php endif; ?>
        <div class="col-md-6"><strong>Internship Period:</strong> <?= htmlspecialchars($startDate) ?> to <?= htmlspecialchars($endDate) ?></div>
        <div class="col-md-6"><strong>Employer:</strong> <?= htmlspecialchars($employer) ?></div>
        <div class="col-md-6"><strong>Employer Dept:</strong> <?= htmlspecialchars($employerDept) ?></div>
        <div class="col-md-6"><strong>Joining Date:</strong> <?= htmlspecialchars($joining) ?></div>
    </div>

    <hr>
    <p class="text-muted small">
        This admit card is digitally signed and issued by ProSensia. No physical stamp required.<br>
        Verification timestamp: <?= date('Y-m-d H:i:s') ?>
    </p>
    <div class="text-center mt-3">
        <a href="<?= htmlspecialchars($pdfUrl) ?>" class="btn btn-warning btn-sm" target="_blank">
            <i class="bi bi-download"></i> Download Admit Card (PDF)
        </a>
    </div>
</div>
</body>
</html>