<?php
// Form C — Internship Placement Proforma — PDF with automatic signature & stamp images
require_once __DIR__ . '/../includes/auth.php';
require_login();
require_once __DIR__ . '/../lib/fpdf.php';

$me = current_user();
$role = $me['role'];

// Determine which user's form to show
$target = (in_array($role, ['super_admin', 'management']) && !empty($_GET['uid'])) ? (int)$_GET['uid'] : $me['id'];

$u = $pdo->prepare('SELECT u.*, p.* FROM users u LEFT JOIN profiles p ON p.user_id = u.id WHERE u.id = ?');
$u->execute([$target]);
$student = $u->fetch();
if (!$student) {
    http_response_code(404);
    exit('Student not found');
}

$fc = $pdo->prepare('SELECT * FROM form_c WHERE user_id = ?');
$fc->execute([$target]);
$f = $fc->fetch();

// Intern can only download if form is approved; admin can always download
if ($role === 'intern' && (!$f || $f['status'] !== 'approved')) {
    http_response_code(403);
    exit('Form C not approved yet. You can download only after super admin approval.');
}

$logo_rel     = setting('logo_path', 'assets/img/prosensia-logo.png');
$partner_rel  = setting('partner_logo_path', '');
$logo         = __DIR__ . '/../' . $logo_rel;
$partner      = $partner_rel ? __DIR__ . '/../' . $partner_rel : null;

// Paths to stamp PNG images (place your own files in assets/img/)
$employerStamp = __DIR__ . '/../assets/img/employer-stamp.png';
$hodStamp      = __DIR__ . '/../assets/img/hod-stamp.png';

class ProformaPDF extends FPDF
{
    public $logo;
    public $partner;
    public $org = 'ProSensia';
    public $employerStamp;
    public $hodStamp;

    function Header()
    {
        if ($this->logo && file_exists($this->logo)) {
            $this->Image($this->logo, 12, 8, 36);
        }
        if ($this->partner && file_exists($this->partner)) {
            $this->Image($this->partner, 162, 8, 36);
        }
        $this->SetFont('Helvetica', 'B', 16);
        $this->SetXY(0, 14);
        $this->Cell(0, 8, 'Internship Placement Proforma', 0, 1, 'C');
        $this->SetFont('Helvetica', '', 10);
        $this->SetTextColor(90, 90, 90);
        $this->Cell(0, 5, $this->org . ' - Internship Programme', 0, 1, 'C');
        $this->SetTextColor(0, 0, 0);
        $this->Ln(8);
        $this->SetDrawColor(212, 168, 76);
        $this->SetLineWidth(0.5);
        $this->Line(12, $this->GetY(), 198, $this->GetY());
        $this->Ln(4);
    }

    function Footer()
    {
        $this->SetY(-14);
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(120, 120, 120);
        $this->Cell(0, 5, 'Generated by ProSensia Portal - Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
    }

    function field($label, $value, $w = 190, $h = 8)
    {
        $this->SetFont('Helvetica', 'B', 10);
        $this->Cell(48, $h, $label . ':', 0, 0);
        $this->SetFont('Helvetica', '', 10);
        $val = ($value !== '' && $value !== null) ? (string)$value : str_repeat('_', 60);
        $this->Cell($w - 48, $h, $val, 'B', 1);
    }

    function sectionTitle($t)
    {
        $this->Ln(3);
        $this->SetFillColor(245, 238, 222);
        $this->SetFont('Helvetica', 'B', 11);
        $this->Cell(0, 7, '  ' . $t, 0, 1, 'L', true);
        $this->Ln(2);
    }
}

$pdf = new ProformaPDF('P', 'mm', 'A4');
$pdf->logo          = $logo;
$pdf->partner       = $partner;
$pdf->employerStamp = $employerStamp;
$pdf->hodStamp      = $hodStamp;
$pdf->AliasNbPages();
$pdf->SetMargins(12, 38, 12);
$pdf->SetAutoPageBreak(true, 18);
$pdf->AddPage();

// ---------- Student Information ----------
$pdf->sectionTitle('Student Information');
$pdf->field('Student Name', $student['name']);
$pdf->field('Father Name', $student['father_name']);
$pdf->field('Registration Number', $student['reg_number']);
$pdf->field('Department', $student['department'] ?: 'Electrical and Computer Engineering');
$pdf->field('CNIC #', $student['cnic']);
$pdf->field('Contact number', $student['phone']);
$pdf->field('Email', $student['email']);
$pdf->field('Internship semester', $student['semester']);

$pdf->SetFont('Helvetica', 'B', 10);
$pdf->Cell(48, 8, 'Present Address:', 0, 0);
$pdf->SetFont('Helvetica', '', 10);
$addr = $student['address'] ?: str_repeat('_', 60);
$pdf->MultiCell(142, 6, $addr, 'B');

// ---------- Employer Section ----------
$pdf->sectionTitle('To be filled by Internship Industry/Organization Representative');
$pdf->field('Internship employer name', $f['employer_name'] ?? '');
$pdf->field('Internship department', $f['employer_dept'] ?? '');
$pdf->field('Joining date', $f['joining_date'] ?? '');
$dates = ($f['start_date'] ?? '') . '   to   ' . ($f['end_date'] ?? '');
$pdf->field('Dates of internship', $dates);

// ---------- Declaration ----------
$pdf->Ln(4);
$pdf->SetFont('Helvetica', 'I', 9);
$pdf->SetTextColor(60, 60, 60);
$pdf->MultiCell(0, 5, 'I hereby declare that the above-mentioned information is correct to the best of my knowledge.');
$pdf->SetTextColor(0, 0, 0);

// ---------- Signature & Stamp blocks (with automatic PNG images) ----------
$pdf->Ln(18);
$y = $pdf->GetY();

// Draw signature lines
$pdf->SetFont('Helvetica', '', 10);
$pdf->Line(20, $y, 90, $y);
$pdf->Line(120, $y, 190, $y);
$pdf->SetXY(20, $y + 1);
$pdf->Cell(70, 6, 'Approval of Employer', 0, 0, 'C');
$pdf->SetXY(120, $y + 1);
$pdf->Cell(70, 6, 'Approval by HoD / Chairman', 0, 1, 'C');

// Add stamp PNG images if they exist
if (file_exists($pdf->employerStamp)) {
    $pdf->Image($pdf->employerStamp, 50, $y - 12, 30);
}
if (file_exists($pdf->hodStamp)) {
    $pdf->Image($pdf->hodStamp, 145, $y - 12, 30);
}

$pdf->SetX(20);
$pdf->SetFont('Helvetica', 'I', 8);
$pdf->SetTextColor(120, 120, 120);
$pdf->Cell(70, 4, '(Signature and Stamp)', 0, 0, 'C');
$pdf->SetX(120);
$pdf->Cell(70, 4, '(Signature and Stamp)', 0, 1, 'C');
$pdf->SetTextColor(0, 0, 0);

// Output PDF
$filename = 'FormC_' . preg_replace('/[^A-Za-z0-9_-]/', '_', $student['name']) . '.pdf';
$pdf->Output('I', $filename);