<?php
// DEBUG VERSION - Remove after fixing
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require_once __DIR__ . '/../includes/auth.php';
require_login();

// Test if FPDF exists
if (!file_exists(__DIR__ . '/../lib/fpdf.php')) {
    die('FPDF library not found at ' . __DIR__ . '/../lib/fpdf.php');
}
require_once __DIR__ . '/../lib/fpdf.php';

$me = current_user();
$role = $me['role'];

$target = (in_array($role, ['super_admin', 'management']) && !empty($_GET['uid'])) ? (int)$_GET['uid'] : $me['id'];

// Fetch data
$u = $pdo->prepare('SELECT u.*, p.* FROM users u LEFT JOIN profiles p ON p.user_id = u.id WHERE u.id = ?');
$u->execute([$target]);
$student = $u->fetch();
if (!$student) {
    http_response_code(404);
    exit('Student not found');
}

$fc = $pdo->prepare('SELECT * FROM form_c WHERE user_id = ?');
$fc->execute([$target]);
$f = $fc->fetch();

if ($role === 'intern' && (!$f || $f['status'] !== 'approved')) {
    http_response_code(403);
    exit('Form C not approved yet.');
}

// Generate reference number
$refNumber = 'ProSensiaB' . str_pad(3000 + (int)($f['id'] ?? 0), 4, '0', STR_PAD_LEFT);

// Build absolute verification URL
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'];
$requestUri = $_SERVER['REQUEST_URI'];
$scriptDir = dirname($requestUri);
$baseUrl = $protocol . '://' . $host;
$verifyUrl = $baseUrl . '/verify_formc.php?ref=' . urlencode($refNumber);

// QR code temp file
$tempDir = __DIR__ . '/../temp';
if (!is_dir($tempDir)) mkdir($tempDir, 0775, true);
$qrTempFile = $tempDir . '/qr_' . uniqid() . '.png';
$qrOk = false;

// Try fallback QR (no external library required)
$qrUrl = 'https://quickchart.io/qr?text=' . urlencode($verifyUrl) . '&size=200&margin=2';
$qrData = @file_get_contents($qrUrl);
if ($qrData !== false && file_put_contents($qrTempFile, $qrData)) {
    $qrOk = true;
} else {
    $qrTempFile = null;
}

// Partner logo - safely
$partnerLogoPath = null;
// We need to get setting from database directly because setting() may not exist
$stmt = $pdo->prepare("SELECT v FROM settings WHERE k = 'partner_logo_path'");
$stmt->execute();
$partnerLogoSetting = $stmt->fetchColumn();
if ($partnerLogoSetting) {
    $fullPath = __DIR__ . '/../' . ltrim($partnerLogoSetting, '/');
    if (file_exists($fullPath)) {
        $partnerLogoPath = $fullPath;
    }
}

class ExactFormC extends FPDF
{
    public $partnerLogo;
    public $refNumber;
    public $qrFile;
    
    function Header() {}
    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(128);
        $this->Cell(0, 5, 'Generated by ProSensia Portal - Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
    }
}

$pdf = new ExactFormC('P', 'mm', 'A4');
$pdf->partnerLogo = $partnerLogoPath;
$pdf->refNumber = $refNumber;
$pdf->qrFile = $qrOk ? $qrTempFile : null;
$pdf->AliasNbPages();
$pdf->SetMargins(15, 15, 15);
$pdf->AddPage();
$pdf->SetFont('Helvetica', '', 10);

// ==================== TOP SECTION ====================
if ($pdf->partnerLogo) {
    $pdf->Image($pdf->partnerLogo, 15, 15, 40);
} else {
    $pdf->SetXY(15, 15);
    $pdf->SetFont('Helvetica', 'B', 10);
    $pdf->Cell(40, 10, 'Pak-Austria Fachhochschule', 0, 0, 'L');
}
$pdf->SetY(15);
$pdf->SetX(150);
$pdf->SetFont('Helvetica', 'B', 11);
$pdf->Cell(45, 8, 'Ref: ' . $pdf->refNumber, 0, 1, 'R');

$pdf->SetY(25);
$pdf->SetFont('Helvetica', 'B', 12);
$pdf->Cell(0, 6, 'Pak-Austria Fachhochschule: Institute of Applied Sciences and Technology, Mang, Haripur, KPK', 0, 1, 'C');
$pdf->SetFont('Helvetica', '', 9);
$pdf->Cell(0, 5, 'Website: https://www.paf-iast.edu.pk, Tel: +92-995-645112-116, Fax: +92-995-645117', 0, 1, 'C');
$pdf->Ln(4);
$pdf->SetFont('Helvetica', 'B', 14);
$pdf->Cell(0, 8, 'Internship Placement Proforma', 0, 1, 'C');
$pdf->Ln(6);

// Student Information
$pdf->SetFont('Helvetica', 'B', 11);
$pdf->Cell(0, 8, 'Student Information:', 0, 1);
$pdf->SetFont('Helvetica', '', 10);

$left = 15;
$right = 105;
$lineH = 8;
$yStart = $pdf->GetY();

$pdf->SetXY($left, $yStart);
$pdf->Cell(35, $lineH, 'Student Name:', 0, 0);
$pdf->Cell(55, $lineH, $student['name'] ?: '_________________________', 0, 0);
$pdf->SetXY($right, $yStart);
$pdf->Cell(35, $lineH, 'Father Name:', 0, 0);
$pdf->Cell(55, $lineH, $student['father_name'] ?: '_________________________', 0, 1);

$yStart = $pdf->GetY();
$pdf->SetXY($left, $yStart);
$pdf->Cell(35, $lineH, 'Registration #:', 0, 0);
$pdf->Cell(55, $lineH, $student['reg_number'] ?: '_________________________', 0, 0);
$pdf->SetXY($right, $yStart);
$pdf->Cell(35, $lineH, 'Department:', 0, 0);
$pdf->Cell(55, $lineH, $student['department'] ?: 'Electrical and Computer Engineering', 0, 1);

$yStart = $pdf->GetY();
$pdf->SetXY($left, $yStart);
$pdf->Cell(35, $lineH, 'CNIC #:', 0, 0);
$pdf->Cell(55, $lineH, $student['cnic'] ?: '_________________________', 0, 0);
$pdf->SetXY($right, $yStart);
$pdf->Cell(35, $lineH, 'Contact number:', 0, 0);
$pdf->Cell(55, $lineH, $student['phone'] ?: '_________________________', 0, 1);

$yStart = $pdf->GetY();
$pdf->SetXY($left, $yStart);
$pdf->Cell(35, $lineH, 'Email:', 0, 0);
$pdf->Cell(55, $lineH, $student['email'] ?: '_________________________', 0, 0);
$pdf->SetXY($right, $yStart);
$pdf->Cell(35, $lineH, 'Internship semester:', 0, 0);
$pdf->Cell(55, $lineH, $student['semester'] ?: '_________________________', 0, 1);

$yStart = $pdf->GetY();
$pdf->SetXY($left, $yStart);
$pdf->Cell(35, $lineH, 'Present Address:', 0, 0);
$pdf->MultiCell(160, $lineH, $student['address'] ?: '_________________________', 0, 'L');
$pdf->Ln(4);

// Employer Section
$pdf->SetFont('Helvetica', 'B', 11);
$pdf->Cell(0, 8, 'To be filled by Internship Industry/Organization Representative', 0, 1);
$pdf->SetFont('Helvetica', '', 10);

$yStart = $pdf->GetY();
$pdf->SetXY($left, $yStart);
$pdf->Cell(50, $lineH, 'Internship employer name:', 0, 0);
$pdf->Cell(130, $lineH, $f['employer_name'] ?: '_________________________', 0, 1);

$yStart = $pdf->GetY();
$pdf->SetXY($left, $yStart);
$pdf->Cell(50, $lineH, 'Internship department:', 0, 0);
$pdf->Cell(130, $lineH, $f['employer_dept'] ?: '_________________________', 0, 1);

$yStart = $pdf->GetY();
$pdf->SetXY($left, $yStart);
$pdf->Cell(50, $lineH, 'Joining date:', 0, 0);
$pdf->Cell(130, $lineH, $f['joining_date'] ?: '_________________________', 0, 1);

$yStart = $pdf->GetY();
$pdf->SetXY($left, $yStart);
$pdf->Cell(50, $lineH, 'Dates of internship:', 0, 0);
$dates = ($f['start_date'] ?? '') . '   to   ' . ($f['end_date'] ?? '');
$pdf->Cell(130, $lineH, $dates ?: '_________________________', 0, 1);
$pdf->Ln(8);

// Declaration
$pdf->SetFont('Helvetica', 'I', 10);
$pdf->MultiCell(0, 6, 'I hereby declare that the above-mentioned information is correct to the best of my knowledge.');
$pdf->Ln(8);

// Digital signature notice
$pdf->SetFont('Helvetica', '', 10);
$pdf->MultiCell(0, 6, 'This document is digitally signed and requires no physical stamp as it is generated directly from the ProSensia portal.');
$pdf->Ln(4);
$pdf->SetFont('Helvetica', 'B', 10);
$pdf->Cell(0, 6, 'Digitally Signed by ProSensia', 0, 1, 'L');
$pdf->SetFont('Helvetica', '', 9);
$pdf->Cell(0, 5, 'Date: ' . date('Y-m-d H:i:s'), 0, 1, 'L');
$pdf->Ln(8);

// QR Code
if ($pdf->qrFile && file_exists($pdf->qrFile)) {
    $pdf->Image($pdf->qrFile, 160, $pdf->GetY() + 5, 30);
    $pdf->SetXY(160, $pdf->GetY() + 38);
    $pdf->SetFont('Helvetica', 'I', 7);
    $pdf->Cell(30, 4, 'Scan to verify', 0, 0, 'C');
    register_shutdown_function(function() use ($qrTempFile) {
        if (file_exists($qrTempFile)) @unlink($qrTempFile);
    });
}

// Signature lines
$y = $pdf->GetY() + 20;
$pdf->SetFont('Helvetica', '', 10);
$pdf->Line(20, $y, 90, $y);
$pdf->Line(120, $y, 190, $y);
$pdf->SetXY(20, $y + 2);
$pdf->Cell(70, 6, 'Approval of Employer', 0, 0, 'C');
$pdf->SetXY(120, $y + 2);
$pdf->Cell(70, 6, 'Approval by HoD / Chairman', 0, 1, 'C');
$pdf->SetXY(20, $y + 8);
$pdf->SetFont('Helvetica', 'I', 8);
$pdf->Cell(70, 4, '(Digital signature on file)', 0, 0, 'C');
$pdf->SetXY(120, $y + 8);
$pdf->Cell(70, 4, '(Digital signature on file)', 0, 1, 'C');

$filename = 'FormC_' . preg_replace('/[^A-Za-z0-9_-]/', '_', $student['name']) . '.pdf';
$pdf->Output('I', $filename);