<?php
// formc_pdf.php — Form C PDF matching PAF-IAST Internship Placement Proforma layout.
// QR code replaces the employer's Stamp/Sign box.
require_once __DIR__ . '/../includes/auth.php';
require_login();
require_once __DIR__ . '/../lib/fpdf.php';

$me   = current_user();
$role = $me['role'];

$target = (in_array($role, ['super_admin', 'management']) && !empty($_GET['uid']))
        ? (int)$_GET['uid'] : $me['id'];

$uq = $pdo->prepare('SELECT u.*, p.* FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.id=?');
$uq->execute([$target]); $student = $uq->fetch();
if (!$student) exit('Student not found.');

$fcq = $pdo->prepare('SELECT * FROM form_c WHERE user_id=?');
$fcq->execute([$target]); $f = $fcq->fetch();

if ($role === 'intern' && (!$f || $f['status'] !== 'approved')) exit('Form C is not yet approved.');

$refNumber = 'PAF-PS-' . str_pad(4000 + (int)($f['id'] ?? 0), 5, '0', STR_PAD_LEFT);
$protocol  = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$verifyUrl = $protocol . '://' . $_SERVER['HTTP_HOST'] . '/verify_formc.php?ref=' . urlencode($refNumber);

// ── Temp dir ──────────────────────────────────────────────────────────────────
$tempDir = __DIR__ . '/../temp';
if (!is_dir($tempDir)) mkdir($tempDir, 0777, true);

// ── QR code (verification URL) ────────────────────────────────────────────────
$qrFile = null;
$qrData = @file_get_contents('https://quickchart.io/qr?text=' . urlencode($verifyUrl) . '&size=180&margin=2');
if ($qrData) {
    $qrFile = $tempDir . '/qr_' . uniqid() . '.png';
    file_put_contents($qrFile, $qrData);
    register_shutdown_function(function() use ($qrFile) { @unlink($qrFile); });
}

// ── Helper: resolve logo to a temp PNG ───────────────────────────────────────
function resolve_logo(string $path, string $tempDir): ?string {
    if (!file_exists($path)) return null;
    $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
    if (in_array($ext, ['jpg','jpeg','png','gif'])) return $path;
    if ($ext === 'webp' && function_exists('imagecreatefromwebp')) {
        $img = imagecreatefromwebp($path);
        if (!$img) return null;
        $tmp = $tempDir . '/logo_' . uniqid() . '.png';
        imagepng($img, $tmp); imagedestroy($img);
        register_shutdown_function(function() use ($tmp) { @unlink($tmp); });
        return $tmp;
    }
    return null;
}

// ProSensia logo (black version preferred for print)
$proLogo = null;
foreach ([
    __DIR__ . '/../assets/img/prosensia-logo-black.png',
    __DIR__ . '/../assets/img/prosensia-logo.png',
] as $try) {
    $resolved = resolve_logo($try, $tempDir);
    if ($resolved) { $proLogo = $resolved; break; }
}
if (!$proLogo) {
    $logoPath = $pdo->query("SELECT v FROM settings WHERE k='logo_path'")->fetchColumn();
    if ($logoPath) $proLogo = resolve_logo(__DIR__ . '/../' . ltrim($logoPath, '/'), $tempDir);
}

// Partner logo (university)
$partnerLogo = null;
$partnerPath = $pdo->query("SELECT v FROM settings WHERE k='partner_logo_path'")->fetchColumn();
if ($partnerPath) $partnerLogo = resolve_logo(__DIR__ . '/../' . ltrim($partnerPath, '/'), $tempDir);

// ── FPDF setup ────────────────────────────────────────────────────────────────
class FormCPdf extends FPDF {
    function Header() {}
    function Footer() {
        $this->SetY(-12);
        $this->SetFont('Helvetica','I',7);
        $this->Cell(0,5,'Generated by ProSensia Portal | Ref: ' . $GLOBALS['refNumber'] . ' | Page ' . $this->PageNo() . '/{nb}',0,0,'C');
    }
}

$pdf = new FormCPdf('P','mm','A4');
$pdf->AliasNbPages();
$pdf->SetMargins(15, 12, 15);
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 18);

$pw = 180; // printable width (210 - 30 margins)

// ── Helper: draw a labelled field row (label + underlined value) ──────────────
function row(FPDF &$pdf, $label, $value, $lw = 45, $rw = 0) {
    global $pw;
    if ($rw === 0) $rw = $pw - $lw;
    $h = 7;
    $x = $pdf->GetX(); $y = $pdf->GetY();
    $pdf->SetFont('Helvetica','',9);
    $pdf->Cell($lw, $h, $label, 0, 0, 'L');
    $pdf->SetFont('Helvetica','',9);
    $val = trim((string)$value);
    if ($val === '') {
        // underline placeholder
        $pdf->Cell($rw, $h, '', 'B', 1, 'L');
    } else {
        $pdf->Cell($rw, $h, $val, 'B', 1, 'L');
    }
}

// ── PAGE 1 ────────────────────────────────────────────────────────────────────

// ── Border box ──
$pdf->SetDrawColor(0, 0, 0);
$pdf->SetLineWidth(0.6);
$pdf->Rect(12, 10, 186, 274);

// ── HEADER: PAF-IAST logo (left) + University info parallel to it ────────────
$pdf->SetY(14);

// Partner (PAF-IAST) logo — LEFT side
if ($partnerLogo) {
    $pdf->Image($partnerLogo, 15, 14, 32);
} else {
    $pdf->SetXY(15, 14);
    $pdf->SetFont('Helvetica', 'B', 9);
    $pdf->Cell(32, 12, 'PAF-IAST', 0, 0, 'C');
}

// University text block — to the right of the logo, parallel
$pdf->SetXY(50, 14);
$pdf->SetFont('Helvetica', 'B', 10);
$pdf->MultiCell(143, 5.5, 'Pak-Austria Fachhochschule: Institute of Applied Sciences and Technology, Mang, Haripur, KPK', 0, 'C');
$pdf->SetX(50);
$pdf->SetFont('Helvetica', '', 8);
$pdf->MultiCell(143, 4, 'Website: https://www.paf-iast.edu.pk  |  Tel: +92-995-645112-116  |  Fax: +92-995-645117', 0, 'C');

// Ref number right-aligned below university text
$pdf->SetFont('Helvetica', 'I', 7);
$pdf->Cell(0, 4, 'Ref: ' . $refNumber, 0, 1, 'R');

// ── Title ──
$pdf->Ln(3);
$pdf->SetLineWidth(0.4);
$pdf->Line(13, $pdf->GetY(), 196, $pdf->GetY());
$pdf->Ln(2);
$pdf->SetFont('Helvetica', 'B', 13);
$pdf->Cell(0, 8, 'Internship Placement Proforma', 0, 1, 'C');
$pdf->Line(13, $pdf->GetY(), 196, $pdf->GetY());
$pdf->Ln(4);

// ── Section: Student Information ─────────────────────────────────────────────
$pdf->SetFont('Helvetica', 'BU', 10);
$pdf->Cell(0, 6, 'Student Information:', 0, 1);
$pdf->Ln(1);

$h = 7; $left = 15; $right = 108;
$lw1 = 42; $rw1 = 48; $lw2 = 42; $rw2 = 48;

// Row: Student Name | Father Name
$y = $pdf->GetY();
$pdf->SetXY($left, $y);  $pdf->SetFont('Helvetica','',9); $pdf->Cell($lw1,$h,'Student Name:',0,0);
$pdf->SetFont('Helvetica','',9); $pdf->Cell($rw1,$h,$student['name'] ?: '','B',0);
$pdf->SetXY($right,$y);  $pdf->Cell($lw2,$h,'Father Name:',0,0);
$pdf->Cell($rw2,$h,$student['father_name'] ?: '','B',1);

// Row: Registration No | Department
$y = $pdf->GetY();
$pdf->SetXY($left,$y);   $pdf->SetFont('Helvetica','',9); $pdf->Cell($lw1,$h,'Registration No:',0,0);
$pdf->Cell($rw1,$h,$student['reg_number'] ?: '','B',0);
$pdf->SetXY($right,$y);  $pdf->Cell($lw2,$h,'Department:',0,0);
$pdf->Cell($rw2,$h,$student['department'] ?: 'Electrical and Computer Engineering','B',1);

// Row: CNIC | Contact
$y = $pdf->GetY();
$pdf->SetXY($left,$y);   $pdf->Cell($lw1,$h,'CNIC#:',0,0);
$pdf->Cell($rw1,$h,$student['cnic'] ?: '','B',0);
$pdf->SetXY($right,$y);  $pdf->Cell($lw2,$h,'Contact#:',0,0);
$pdf->Cell($rw2,$h,$student['phone'] ?: '','B',1);

// Row: Email | Internship Year
$iy = $student['internship_year'] ?: ($student['semester'] ?: '');
$y = $pdf->GetY();
$pdf->SetXY($left,$y);   $pdf->Cell($lw1,$h,'Email:',0,0);
$pdf->Cell($rw1,$h,$student['email'] ?: '','B',0);
$pdf->SetXY($right,$y);  $pdf->Cell($lw2,$h,'Internship Year:',0,0);
$pdf->Cell($rw2,$h,$iy,'B',1);

// Row: Student Academic Advisor (full width)
$y = $pdf->GetY();
$pdf->SetXY($left,$y);
$pdf->Cell(52,$h,'Student Academic Advisor:',0,0);
$pdf->Cell(128,$h,$student['academic_advisor'] ?: '','B',1);

// Row: Academic Advisor Email & Contact (full width)
$y = $pdf->GetY();
$pdf->SetXY($left,$y);
$adv_contact = trim(($student['academic_advisor_email'] ?: '') . '  ' . ($student['academic_advisor_contact'] ?: ''));
$pdf->Cell(52,$h,'Academic Advisor Email & Contact:',0,0);
$pdf->Cell(128,$h,$adv_contact,'B',1);

// Row: Postal Address (full width)
$y = $pdf->GetY();
$pdf->SetXY($left,$y);
$pdf->Cell(52,$h,'Postal Address:',0,0);
$pdf->Cell(128,$h,$student['address'] ?: '','B',1);

$pdf->Ln(4);

// ── Declaration ───────────────────────────────────────────────────────────────
$pdf->SetFont('Helvetica','I',9);
$pdf->MultiCell(0,5,'I hereby declare that the above-mentioned information is correct to the best of my knowledge.',0,'L');
$pdf->Ln(3);

// Three signature blocks
$pdf->SetFont('Helvetica','',9);
$sig_y = $pdf->GetY() + 12;
$col1 = 15; $col2 = 78; $col3 = 141;
$sig_w = 55;

$pdf->Line($col1, $sig_y, $col1+$sig_w, $sig_y);
$pdf->Line($col2, $sig_y, $col2+$sig_w, $sig_y);
$pdf->Line($col3, $sig_y, $col3+$sig_w, $sig_y);

$pdf->SetXY($col1, $sig_y+1); $pdf->Cell($sig_w,4,'Student signature with date',0,0,'C');
$pdf->SetXY($col2, $sig_y+1); $pdf->Cell($sig_w,4,'Approval by Academic Advisor',0,0,'C');
$pdf->SetXY($col3, $sig_y+1); $pdf->Cell($sig_w,4,'Approval by HoD / Chairman',0,1,'C');

$pdf->SetXY($col2, $sig_y+5); $pdf->SetFont('Helvetica','I',7); $pdf->Cell($sig_w,4,'signature with date',0,0,'C');
$pdf->SetXY($col3, $sig_y+5); $pdf->Cell($sig_w,4,'(Signature and Stamp)',0,1,'C');

$pdf->Ln(8);
$pdf->SetLineWidth(0.5);
$pdf->Line(13, $pdf->GetY(), 196, $pdf->GetY());
$pdf->Ln(3);

// ── Section: Industry Representative ─────────────────────────────────────────
$pdf->SetFont('Helvetica','BU',10);
$pdf->Cell(0, 6, 'To be filled by the Industry Representative', 0, 1);
$pdf->Ln(1);

$pdf->SetFont('Helvetica','',9);
$iw = 180;
$industry_y = $pdf->GetY();

// Employer name
$pdf->SetFont('Helvetica','',9);
$pdf->Cell($iw, 7, 'Internship employer name:', 0, 1);
$pdf->Cell($iw, 7, $f['employer_name'] ?: '', 'B', 1);
$pdf->Ln(2);

// Department
$pdf->Cell($iw, 7, 'Internship department:', 0, 1);
$pdf->Cell($iw, 7, $f['employer_dept'] ?: '', 'B', 1);
$pdf->Ln(2);

// Joining date
$pdf->Cell($iw, 7, 'Joining date:', 0, 1);
$pdf->Cell($iw, 7, $f['joining_date'] ?: '', 'B', 1);
$pdf->Ln(2);

// Dates of internship
$dates_str = trim(($f['start_date'] ?? '') . '   to   ' . ($f['end_date'] ?? ''));
$pdf->Cell($iw, 7, 'Dates of internship:', 0, 1);
$pdf->Cell($iw, 7, $dates_str, 'B', 1);
$pdf->Ln(4);

// ── QR + Approval box ────────────────────────────────────────────────────────
// The employer's "Approval of Employer (Signature and Stamp)" box is replaced by
// the ProSensia QR code for digital verification.
$approvalBoxX = 15;
$approvalBoxY = $pdf->GetY();
$approvalBoxW = 72;
$approvalBoxH = 36;

// Draw box
$pdf->SetDrawColor(80, 80, 80);
$pdf->SetLineWidth(0.4);
$pdf->Rect($approvalBoxX, $approvalBoxY, $approvalBoxW, $approvalBoxH);

// QR inside box
if ($qrFile && file_exists($qrFile)) {
    $qrW = 28;
    $qrX = $approvalBoxX + ($approvalBoxW - $qrW) / 2 - 8;
    $pdf->Image($qrFile, $qrX, $approvalBoxY + 2, $qrW);
    $pdf->SetXY($approvalBoxX, $approvalBoxY + $qrW + 4);
    $pdf->SetFont('Helvetica','I',6);
    $pdf->Cell($approvalBoxW, 4, 'Scan to verify - Ref: ' . $refNumber, 0, 1, 'C');
    $pdf->SetFont('Helvetica','',7);
    $pdf->SetX($approvalBoxX);
    $pdf->Cell($approvalBoxW, 3, 'Digitally approved by ProSensia', 0, 1, 'C');
} else {
    $pdf->SetXY($approvalBoxX + 2, $approvalBoxY + 4);
    $pdf->SetFont('Helvetica','B',9);
    $pdf->Cell($approvalBoxW-4, 5, 'Approval of Employer', 0, 1, 'C');
    $pdf->SetFont('Helvetica','I',8);
    $pdf->SetX($approvalBoxX + 2);
    $pdf->Cell($approvalBoxW-4, 4, '(Digital Stamp - ProSensia)', 0, 1, 'C');
    $pdf->SetFont('Helvetica','',7);
    $pdf->SetX($approvalBoxX + 2);
    $pdf->Cell($approvalBoxW-4, 4, 'Ref: ' . $refNumber, 0, 1, 'C');
}

// Box label below
$pdf->SetXY($approvalBoxX, $approvalBoxY + $approvalBoxH + 1);
$pdf->SetFont('Helvetica','',8);
$pdf->Cell($approvalBoxW, 5, 'Approval of Employer', 0, 1, 'C');

// ProSensia details to the right of the box
$detailX = $approvalBoxX + $approvalBoxW + 8;
$pdf->SetXY($detailX, $approvalBoxY + 2);
$pdf->SetFont('Helvetica','B',9);
$pdf->Cell(90, 5, 'ProSensia', 0, 1, 'L');
$pdf->SetX($detailX);
$pdf->SetFont('Helvetica','',8);
$pdf->Cell(90, 4, 'prosensia.pk | AI - Tech - Innovation', 0, 1, 'L');
$pdf->SetX($detailX);
$pdf->Cell(90, 4, 'Date: ' . date('d-M-Y', strtotime($f['submitted_at'] ?? 'now')), 0, 1, 'L');
$pdf->SetX($detailX);
$pdf->SetFont('Helvetica','I',8);
$pdf->Cell(90, 4, 'This document is electronically verified.', 0, 1, 'L');

$pdf->Output('I', 'FormC_' . preg_replace('/[^A-Za-z0-9_-]/', '_', $student['name'] ?? 'intern') . '.pdf');
